### ISSUE TITLE
As a user who uses this program a lot, I would like to be able to customise my list of favourite commands ... 

### ISSUE THREAD

**Issue by EthanWong2212** [AY2021S1-CS2113T-F14-3/tp#66]
... So that I can change the list according to my needs

- [x] /addfav [description] →  store previous command + a description (can be empty)
- [x] /deletefav [index] → delete fav
- [x] /execfav [list index] → execute fav cmd
- [x] /listfav → display all favourites with index
- [x] /descfav [index /to desc] → change description for fav

**Comment by wamikamalik** [comment]
Done!
